MAX_POINT = 1250
MAX_NODE_IN_ROUTE = 100
DEFAULT_SEED = 42
V_NUM_RELAX = 3

INF = 2 ** 31 - 1
N = 8192
NO_LIMIT = -1
G_1 = 500
DEFAULT_MAX_ITER = G_1
RUNS = 10
P_SIZE = 64
PRECISION = 0.001
OUTPUT_PER_GENS = 1
DEFAULT_IF_OUTPUT = False

DEFAULT_PRUNING = False

DEFAULT_LS_PROB = 1.0
DEFAULT_O_1_EVAL = False
DEFAULT_2_OPT_STAR = True
DEFAULT_2_OPT = False
DEFAULT_OR_OPT = False
DEFAULT_2_EX = False
DEFAULT_OR_OPT_LEN = 3
DEFAUTL_EX_LEN = 2
DEFAULT_SKIP_FINDING_LO = False

DEFAULT_ELO = 1
DEFAULT_DESTROY_RATIO_L = 0.2
DEFAULT_DESTROY_RATIO_U = 0.4
DEFAULT_RD_REMOVAL = False
DEFAULT_RT_REMOVAL = False
DEFAULT_GD_INSERTION = False
DEFAULT_RG_INSERTION = False
DEFAULT_RD_R_I = False

RCRS = "rcrs"
RCRS_RANDOM = "rcrs_random"
TD = "td"
REGRET = "regret"

DEFAULT_INIT = RCRS
DEFAULT_CROSSOVER = RCRS

K = -1

CIRCLE = "circle"
TOURNAMENT = "tournament"
RDSELECTION = "rdslection"
DEFAULT_SEL = CIRCLE

DEFAULT_NO_CROSSOVER = False

ONE_ON_ONE = "one_on_one"
ELITISM_1 = "elitism"
DEFAULT_REPLACEMENT = ONE_ON_ONE

DEFAULT_ALPHA = 1.0
PENALTY_FACTOR = 10.0

INFEASIBLE = -1

BENCHMARKING_O_1_EVAL = False

FITNESS_VEHICLE_WEIGHT = 2000.0
FITNESS_DISTANCE_WEIGHT = 1.0

DEFAULT_PARALLEL_WORKERS = 0
DEFAULT_LOCAL_SEARCH_INTERVAL = 25
DEFAULT_STAGNATION_INTERVAL = 50
DEFAULT_DIVERSIFY_RATIO = 0.40
DEFAULT_SHO_MUTATION_PROB = 0.35
HYBRID_MODE_PH_SHOWOA = "ph_showoa"
HYBRID_MODE_SHO = "sho"
HYBRID_MODE_WOA = "woa"
DEFAULT_HYBRID_MODE = HYBRID_MODE_PH_SHOWOA

COMPUTE_BACKEND_AUTO = "auto"
COMPUTE_BACKEND_CPU = "cpu"
COMPUTE_BACKEND_CUDA = "cuda"
DEFAULT_COMPUTE_BACKEND = COMPUTE_BACKEND_AUTO
